application: cosine-gaming
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static
- url: /host
  static_dir: static/host
- url: /ld32
  static_dir: static/ld32

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: latest
