#application: cosine-gaming
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /swarm/(.*\..*)
  static_files: static/swarm/\1
  upload: static/swarm/.*
- url: /swarm/play
  static_files: static/swarm/game.html
  upload: static/swarm/game.html
- url: /pale-white-dot/
  static_files: static/pwd/index.html
  upload: static/pwd/index.html
  expiration: "10m"

- url: /host
  static_dir: static/host
  expiration: "10m" # People will only access this once, and I might update
- url: /ld32
  static_dir: static/ld32
  expiration: "365d"
- url: /Revenge/resources
  static_dir: static/revengeSounds
- url: /pale-white-dot/
  static_dir: static/pwd
  expiration: "7d"
- url: /static/pwd-post
  static_dir: static/pwd
  expiration: "7d"
- url: /static/pale-white-dot
  static_dir: static/pwd-ld
  expiration: "365d" # I'll never change this directory
- url: /static
  static_dir: static

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?[Tt]humbs\.db$
- ^(.*/)?.*\.psd$
