#application: cosine-gaming
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static
- url: /host
  static_dir: static/host
- url: /ld32
  static_dir: static/ld32
- url: /Revenge/resources
  static_dir: static/revengeSounds

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /swarm/(.*\..*)
  static_files: static/swarm/\1
  upload: static/swarm/.*
- url: /swarm/play
  static_files: static/swarm/game.html
  upload: static/swarm/game.html

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?[Tt]humbs\.db$
- ^(.*/)?.*\.psd$
